### ISSUE TITLE
Send down id token to the react SDK

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-react-sdk#32]
### Problem

We may want to display user information in the react app. The proper way to do that is to use an id_token. 

### Solution

We should send the id token down to the react app as a non http only cookie.

### Alternatives/workarounds

The user object may have that data. See https://github.com/FusionAuth/fusionauth-react-sdk/issues/22 as well.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by JakeLo123** [comment]
No changes to the SDK required for this one.
- I'm observing that the FusionAuth hosted callback endpoint sets this cookie as `app.idt` -- thus sends it to the react (or whatever framework) SDK. Then removes it on logout.
- The documentation for this SDK specifies that this cookie needs set at `GET /app/callback`

If one of my colleagues is in agreement, we can go ahead and close this issue.

**Comment by david-chalk** [comment]
@JakeLo123 I believe you're correct in assessing that we can close this issue. I see `app.idt` being set and deleted via the FusionAuth server.
