### ISSUE TITLE
Work with FusionAuth core hosted endpoints

### ISSUE THREAD

**Issue by bhalsey** [FusionAuth/fusionauth-react-sdk#34]
### Problem
Using the React SDK requires hosting server endpoints.  The only compatible solution right now is in https://github.com/FusionAuth/fusionauth-example-react-sdk

### Solution
When FusionAuth adds functionality to host these endpoints, the react sdk should work with this out of the box.

### Alternatives/workarounds
Use the `example-react-sdk / server`

### Additional context
https://github.com/FusionAuth/fusionauth-issues/issues/1943

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by JakeLo123** [comment]
The SDK now comes with out-of-the-box support for core endpoints [login, register, logout, tokenRefresh]. However, the README is outdated - it says setting up your own server is a requirement.

It would be great for the README to document both ways of interacting with the SDK. Closing this issue and opening https://github.com/FusionAuth/fusionauth-react-sdk/issues/65 as a followup.

**Comment by JakeLo123** [comment]
The SDK now comes with out-of-the-box support for core endpoints [login, register, logout, tokenRefresh]. However, the README is outdated - it says setting up your own server is a requirement.

It would be great for the README to document both ways of interacting with the SDK. Closing this issue and opening https://github.com/FusionAuth/fusionauth-react-sdk/issues/65 as a followup.
