### ISSUE TITLE
Why is `Content-Type` set for empty requests? 

### ISSUE THREAD

**Issue by osbornm** [FusionAuth/fusionauth-react-sdk#44]
Currently when making a `POST` to the `/jwt-refresh` endpoint the request gets a `content-type` set to `application/json` (see: https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/src/providers/FusionAuthProvider.tsx#L141-L149). This seems odd since there is no BODY on the request. This can cause problems in some backends as they might choose to valid a body based on the the `content-type`. For example the default JSON parser in fastify (a node backend) throws if there is no body (see: https://github.com/fastify/fastify/blob/a4b21f0a2e7e753e9a8772dbac6b255b7dcbdc6b/test/helper.js#L316-L335).

I see to possible solutions to this. 

1. Don't set the `content-type`
2. If the idea was to set this to eventually pass something in the body but that was never implemented you could just set the body as an empty object for now. 

Please let me know your thoughts.

**Comment by osbornm** [comment]
@robotdan another one for you :)

**Comment by osbornm** [comment]
Thoughts @bhalsey @mooreds or @sam-woodridge

**Comment by bhalsey** [comment]
Thank you for opening this issue, @osbornm.  I've created  https://github.com/FusionAuth/fusionauth-react-sdk/pull/45 to address this.

**Comment by bhalsey** [comment]
PR has been merged.
