### ISSUE TITLE
refreshToken() does not work without implicitly setting tokenRefreshPath

### ISSUE THREAD

**Issue by todda00** [FusionAuth/fusionauth-react-sdk#55]
### Description 
When using the Hosted Backend, the endpoint URL for token refresh is `/app/refresh/{clientId}` but the React SDK is sending the refresh attempt to `/app/refresh`. 

When the provider is set with a `tokenRefreshPath` which includes the clientId, the refresh works as expected. 

Not working:
```
<FusionAuthProvider
  clientID="4dff639c-d360-427a-b742-d108a2229002"
  serverUrl="http://localhost:9011"
  redirectUri="http://localhost:4000"
>
```

Working:
```
<FusionAuthProvider
  clientID="4dff639c-d360-427a-b742-d108a2229002"
  serverUrl="http://localhost:9011"
  redirectUri="http://localhost:4000"
  tokenRefreshPath="/app/refresh/4dff639c-d360-427a-b742-d108a2229002"
>
```

### Affects versions
`"@fusionauth/react-sdk": "^0.25.0"`
Fusion Auth w/ Hosted Backend API @ 1.47.1

### Expected behavior
I expect the clientId to be included in the refresh URL without having to set the `tokenRefreshPath`

**Comment by stephan-playbk** [comment]
Just ran into the same issue on 
```
"@fusionauth/react-sdk": "^0.26.0"
FA Version: 1.47.1
```

Thanks for the workaround!

**Comment by mooreds** [comment]
Thanks for filing this, @todda00 ! We should update the app refresh logic to automatically apply a client ID.
