### ISSUE TITLE
customize the name of the `isAuthenticated` cookie

### ISSUE THREAD

**Issue by attilah** [FusionAuth/fusionauth-react-sdk#57]
Option to customize the cookie name used to check `isAuthenticated`.

### Problem
We're using a different backend implementation, our cookie content and name is different, so `isAuthenticated` will never work for us.

### Solution
Have an option to change the cookie name from `app.at_exp` to something else, so the SDK could still be used as is.

### Alternatives/workarounds
Don't use the SDK and implement our own SDK which is also OK.

**Comment by mooreds** [comment]
The reason for the `app.at_exp` cookie name is to make it compatible with our [hosted backend](https://fusionauth.io/docs/v1/tech/apis/hosted-backend), but a custom seems like a reasonable enhancement. Thanks!

**Comment by JakeLo123** [comment]
[This PR](https://github.com/FusionAuth/fusionauth-react-sdk/pull/69) should fix your issue with `isAuthenticated` not being correct!
The provided `isAuthenticated` value ought to be a function of whether or not the `user` object is set, not the above mentioned cookie.

Nonetheless, we can still add this enhancement 👍 that should be easy
