### ISSUE TITLE
/me fetch failure causing infinite loop

### ISSUE THREAD

**Issue by attilah** [FusionAuth/fusionauth-react-sdk#58]
/me fetch failure causing infinite loop

### Description 
After login when no `user` cookie is present then the user info endpoint is being invoked via a fetch request and if that fetch fails for a reason (CORS, or anything else), and a re-render is triggered, then  it will cause an infinite loop (can be tested with the example app, comment out the alert dialog to see it).

### Affects versions
Latest

### Steps to reproduce
1. Configure a failing userinfo endpoint in the example app
2. Login to the app

### Expected behavior
Have some backoff strategy to stop making the fetch calls and getting information about userinfo failure specifically (because it is a backchannel invocation failure, not a redirect failure) or the ability to pass in a function which can do the userinfo invocation, so the consumers of the SDK has a better control over what to do.

### Screenshots
N/A

**Comment by mooreds** [comment]
Thanks for filing this, @attilah
