### ISSUE TITLE
v1.0.5 doesn't contain any code

### ISSUE THREAD

**Issue by stephan-playbk** [FusionAuth/fusionauth-react-sdk#87]
### Description 
Cannot import anything, as there's no code listed under node_modeles/@fusionauth/react-sdk

### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Steps to reproduce
1. install @fusionauth/react-sdk
2. try to import something from the package

### Expected behavior
Package should contain code

### Screenshots
![image](https://github.com/FusionAuth/fusionauth-react-sdk/assets/73884729/654cd1f6-4849-4a92-9811-e0080ed7453b)

### Platform
(Please complete the following information)
 - Device: Desktop
 - OS: NixOs
 - All browsers
 - PostgreSQL

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
Workaround is to install v1.0.0

**Comment by mooreds** [comment]
@stephan-playbk thanks so much for filing! We've been working to automate our release process and obviously forgot a step. Sorry about that!

**Comment by david-chalk** [comment]
@stephan-playbk

Hey! 

We've fixed the issue in `v1.0.6`. 

Please let us know if you run into any more issues, thank you!
